import './sass/index.scss'
import './js/apiRequest.js'
import './js/header-library.js'
import './js/filmCards-library.js'
import './js/header-home.js'
import './js/filmCards-home.js'
import './js/pagination.js'
import './js/modal.js'
