import './sass/index.scss'
import './js/apiRequest.js'
import './js/headerLibrary.js'
import './js/filmCardsLibrary.js'
import './js/headerHome.js'
import './js/filmCardsHome.js'
import './js/pagination.js'
import './js/modal.js'
import './js/footerModal.js';